# Generated by Django 2.0.5 on 2018-09-17 14:31

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_image'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('hyd', django.db.models.manager.Manager()),
            ],
        ),
    ]
